# Generated by Django 5.0.6 on 2024-07-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverside', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MachResult',
            new_name='MatchResult',
        ),
    ]
